export const LEAF_BACKEND_URL   =   "http://localhost:5000/api/v1"
export const LEAF_USER_ID       =   "LEAF_USER_ID"
export const LEAF_AX_TOKEN      =   "LEAF_ACCESS_TOKEN"
export const LEAF_RF_TOKEN      =   "LEAF_REFRESH_TOKEN"
export const GOOGLE_OAUTH_CLIENT_ID = "1054597230526-7hofjov730t0ihoon3rdk47q37ditj7j.apps.googleusercontent.com"